### PR TITLE
OpenMapSamples redux

### PR DESCRIPTION
**Pull request by adamfranco**
Undo the revert of openmapsamples merge. Needs some npm install fixup to work on a clean node_modules directory.

### CODE REVIEW

**Comment by adamfranco** [comment]
Ok, this PR is now ready for review. I've added a **Test Build** check to on pull requests to ensure that the PR will not break the build.

The big changes upstream in OpenMapSamples are that I moved the demo site to its own package at [OpenMapSamples-examples](https://github.com/adamfranco/OpenMapSamples-examples) to remove as many dependencies as possible from the [OpenMapSamples](https://github.com/adamfranco/OpenMapSamples) library itself and the [OpenMapSamples-MapLibre](https://github.com/adamfranco/OpenMapSamples-MapLibre) control. It turns out that the demo had a dependency on the `dotenv` package which was breaking for some reason after an update and then causing the Americana build to fail. With these extra dependencies removed, builds should be much more stable.

I also added a[ Places sample](https://adamfranco.github.io/OpenMapSamples-examples/?omss=places&omsv=8#8.02/-0.084/-0.012) with a grid of points for each place:
Screen Shot 2022-02-14 at 7 57 14 PM

Places in Americana:
Screen Shot 2022-02-14 at 7 57 51 PM

**Comment by adamfranco** [comment]
PS, the prettier check seems to be failing due to an unrelated CDN error with: http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz

**Comment by ZeLonewolf** [comment]
Awesome!  I think rank only goes up to 10 in OpenMapTiles?

**Comment by adamfranco** [comment]
https://openmaptiles.org/schema/#place says that "the rank field for cities
ranges from 1 to 10 for the most important cities and continues from 10
serially based on the local importance of the city (derived from population
and city class)."

I have no idea where it actually ends.

**Comment by ZeLonewolf** [comment]
Oh yeah that makes sense.  There's code in OpenMapTiles that uses PostGIS's partition function on a per-tile basis.  So it'll rank cities that fall within a tile from 10 and up.

**Comment by ZeLonewolf** [comment]
It looks like the style for motorway and trunk tunnels are swapped:
image

However, the integration (which is what this PR does) looks good to me!

**Review by ZeLonewolf — APPROVED** [review]

**Review by zekefarwell — APPROVED** [review]
Looks good to me.  For real this time! 😄 I deleted my node_modules folder before running `npm install` just to be sure.

**Pull request merged**
