### PR TITLE
Add Nebraska truck and scenic shields

### LINKED ISSUE #649: Nebraska Byway Shield
The Nebraska Byways are marked by a single shield with a second sign below with the nameplate of the byway. At the size at which we display route shields, there’s no need for the name, so we can display just the logo. These turnpikes are tagged network=US:NE:Scenic (although most have not been mapped yet, so that will be an upcoming project for me!).
220px-Nebraska_Byway_Sign_M1-11 svg

### LINKED ISSUE #650: Remove Bulgaria motorway shield
This style currently includes a green shield for `network=bg:national` under the assumption that every route in this network is a motorway or expressway (A-roads). In fact, this `network` tag is primarily being used for Republic Roads (I-roads), which should be marked by blue shields. The motorways and expressways form a separate network that should have a separate `network` tag. We should remove this incorrectly implemented shield, so that the local community can come to a consensus about a less ambiguous tagging scheme without undue influence from this style.

/ref #142

### LINKED ISSUE #651: Nebraska State Truck Routes
State truck route shields do not appear to be rendering properly, at least in Nebraska.
Screenshot 2023-01-02 at 6 05 59 PM

### PR DESCRIPTION
**Pull request by ZeLonewolf**
Fixes #649
Fixes #651

Test location ([localhost link](http://localhost:1776/#map=13/40.26422/-96.74233))
image

### CODE REVIEW

**Comment by ZeLonewolf** [comment]
Whoops, did that one on the wrong branch.

**Comment by ZeLonewolf** [comment]
I've somehow branched this off of the wrong place and I'm not sure how to fix it.

**Comment by ZeLonewolf** [comment]
Thanks!  I think we got this sorted now :grimacing:

**Comment by 1ec5** [comment]
I’d still recommend a rebase. The current state of this branch is likely to introduce a bad merge.

**Comment by ZeLonewolf** [comment]
Ok, I think I got it now.

**Review by 1ec5 — APPROVED** [review]

**Comment by michaelblyons** [comment]
> I've somehow branched this off of the wrong place and I'm not sure how to fix it.

https://github.com/git/git/blob/master/Documentation/git-rebase.txt#L101-L159

**Pull request merged**
