### PR TITLE
Add shields for Croatia

### PR DESCRIPTION
**Pull request by Janjko**
Added shields for Autoceste, Državne ceste, Županijske ceste and Lokalne ceste.

### CODE REVIEW

**Comment by ZeLonewolf** [comment]
Note that the A3 shield is currently doubled because the two sides of the highway have slightly different `name` tags.  When they get coalesced, they're therefore treated as separate routes.  I would consider that a tagging error that should not hold this up.

**Review by ZeLonewolf — APPROVED** [review]
This looks great, thank you for the contribution!

**Comment by claysmalley** [comment]
Thanks for your contribution! Don't forget `npm run status_map` to highlight Croatia on the shield coverage map.

**Comment by Janjko** [comment]
> Note that the A3 shield is currently doubled because the two sides of the highway have slightly different `name` tags. When they get coalesced, they're therefore treated as separate routes. I would consider that a tagging error that should not hold this up. ([tile server location](https://tile.ourmap.us/inspect.html#15/45.74697/16.06601))

It looks great, thanks!

I'll see what are standards with these double routes, they will probably lose a few tags soon.

**Comment by ZeLonewolf** [comment]
> > Note that the A3 shield is currently doubled because the two sides of the highway have slightly different `name` tags.  When they get coalesced, they're therefore treated as separate routes.  I would consider that a tagging error that should not hold this up.
> 
> This will happen anywhere a route relation’s `name` has a [disambiguating suffix](https://community.openstreetmap.org/t/planned-edit-to-re-tag-descriptive-names-in-road-route-relations-in-the-united-states/108454) or [other description](https://community.openstreetmap.org/t/proposal-use-description-instead-of-name-for-route-relations/104656), right?

Yes, if they're different.  This was one of the motivations for the linked edits.

**Review by ZeLonewolf — CHANGES_REQUESTED** [review]
@Janjko please run `npm run status_map` and commit the results

**Comment by Janjko** [comment]
> @Janjko please run `npm run status_map` and commit the results

I wasn't able to do this. I ran it in a docker with the newest node (v22.1.0) and running `npm run status_map` results in:
`
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@americana/maplibre-shield-generator' imported from /src/src/js/shield_defs.js`

Then running `npm install @americana/maplibre-shield-generator` results in:

```
root@43e18cb7f75c:/src# npm install @americana/maplibre-shield-generator
npm warn deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm warn deprecated shortid@2.2.16: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm error code 1
npm error path /src/node_modules/canvas
npm error command failed
npm error command sh -c node-pre-gyp install --fallback-to-build --update-binary
npm error make: Entering directory '/src/node_modules/canvas/build'
npm error   SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node
npm error   COPY Release/canvas-postbuild.node
npm error   CXX(target) Release/obj.target/canvas/src/backend/Backend.o
npm error make: Leaving directory '/src/node_modules/canvas/build'
npm error Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --update-binary --module=/src/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/src/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v127' (1)
...
```

Then I tried to install canvas, but that resulted in further errors, so I tried to install:
`
apt-get install libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++`

And that succeeded, but didn't help with installing canvas, and so on..

So I failed that task..

**Comment by claysmalley** [comment]
Just open [this file](https://github.com/Janjko/openstreetmap-americana/blob/patch-1/doc-img/shield_map_world.svg?short_path=5de9935) in a text editor and add one line between Greece and Iceland:

```suggestion
.gr,
.hr,
.is,
```

It will do the exact same thing as `npm run status_map`, without fussing with dependencies.

**Comment by Janjko** [comment]
There, added .hr

**Review by ZeLonewolf — APPROVED** [review]

**Pull request merged**
