### PR TITLE
Restore Slovenia, Croatia, and Austria shield definitions

### LINKED ISSUE #95: Slovenia national road shield turned into a white rectangle
[Slovenia’s A1 motorway relation](https://www.openstreetmap.org/relation/59655) is tagged `network=SI:AC`, so it should show up as A1. Instead, it shows up as a generic white rectangle:

generic

@Mashin6 added a shield for the `SI:AC` network in 4a9c7a02a9f152def0c1215872aeb6fc00c5f50f, but it fell out of the branch for #72 at some point. [The image](https://github.com/ZeLonewolf/openstreetmap-americana/blob/c24e5e8974a40bb5a524d7e1633f0dd7fb27843c/style/icons/shield40_eu_sl_2.svg) is still present, but it’s unused. I wonder if this also accounts for the errors I see when zoomed out on Europe:

```
Uncaught RangeError: mismatched image size
    sa https://zelonewolf.github.io/openstreetmap-americana/js/maplibre-gl-custom-shields.js:31
    la https://zelonewolf.github.io/openstreetmap-americana/js/maplibre-gl-custom-shields.js:31
    clone https://zelonewolf.github.io/openstreetmap-americana/js/maplibre-gl-custom-shields.js:31
    getGlyphs https://zelonewolf.github.io/openstreetmap-americana/js/maplibre-gl-custom-shields.js:35
    asyncAll https://zelonewolf.github.io/openstreetmap-americana/js/maplibre-gl-custom-shields.js:31
    getGlyphs https://zelonewolf.github.io/openstreetmap-americana/js/maplibre-gl-custom-shields.js:35
    asyncAll https://zelonewolf.github.io/openstreetmap-americana/js/maplibre-gl-custom-shields.js:31
    asyncAll https://zelonewolf.github.io/openstreetmap-americana/js/maplibre-gl-custom-shields.js:31
    getGlyphs https://zelonewolf.github.io/openstreetmap-americana/js/maplibre-gl-custom-shields.js:35
    getGlyphs https://zelonewolf.github.io/openstreetmap-americana/js/maplibre-gl-custom-shields.js:35
    processTask https://zelonewolf.github.io/openstreetmap-americana/js/maplibre-gl-custom-shields.js:31
    receive https://zelonewolf.github.io/openstreetmap-americana/js/maplibre-gl-custom-shields.js:31
```

Maybe someone force-pushed a commit, clobbering someone else’s, or maybe a merge conflict was resolved badly. I don’t think it’s possible to tell exactly what happened because of all the squash-merging that took place. We’ll probably want to go through the other commits to catch anything else that needs to be reapplied.

/ref #69

### PR DESCRIPTION
**Pull request by zekefarwell**
Somehow these got lost in a merge conflict while working through #72

Resolves #95

### CODE REVIEW

**Review by ZeLonewolf — APPROVED** [review]
Looks good!  European shields are so boring looking :-D

**Comment by zekefarwell** [comment]
Not all European shields.  Romania's look awesome!
image

**Comment by Mashin6** [comment]
And Hungarian shields look nice too. But wait, are you saying that you don't like when highway shields look like a random house number sign? :D

**Review by Mashin6 — APPROVED** [review]
Looks good to me.

**Pull request merged**
