### PR TITLE
Replace skia with node-canvas

### PR DESCRIPTION
**Pull request by ZeLonewolf**
This PR replaces skia with node-canvas, which hopefully has better platform support.

### CODE REVIEW

**Comment by jleedev** [comment]
Looks like 62ea2217d8a3524091f49e4ae3b43b91f8daa766 accidentally dropped the dependency on `glob`.

**Review by jleedev — APPROVED** [review]

**Comment by ZeLonewolf** [comment]
Was glob used by anything?  I thought it was vestigal.

**Comment by jleedev** [comment]
https://github.com/ZeLonewolf/openstreetmap-americana/blob/45456a9b45eeceadde8c5db9efa219d90064f81f/scripts/sprites.js#L14

**Comment by jleedev** [comment]
Wowie `color-namer` sure is slow.

**Comment by 1ec5** [comment]
We could always just replace it with:

https://github.com/ZeLonewolf/openstreetmap-americana/blob/45456a9b45eeceadde8c5db9efa219d90064f81f/src/constants/color.js#L47-L59

but in reverse.

**Comment by quincylvania** [comment]
`npm install` fails on my M1 Mac with this change. Looks like there's no arm64 build of node canvas available.

```
npm ERR! code 1
npm ERR! path /Users/quincy/Documents/repos/osmus/openstreetmap-americana/node_modules/canvas
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build --update-binary
npm ERR! Failed to execute '/Users/quincy/.nvm/versions/node/v18.14.0/bin/node /Users/quincy/.nvm/versions/node/v18.14.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/Users/quincy/Documents/repos/osmus/openstreetmap-americana/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/quincy/Documents/repos/osmus/openstreetmap-americana/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.10
npm ERR! node-pre-gyp info using node@18.14.0 | darwin | arm64
npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.0/canvas-v2.11.0-node-v108-darwin-unknown-arm64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.0/canvas-v2.11.0-node-v108-darwin-unknown-arm64.tar.gz
```

**Comment by 1ec5** [comment]
It looks like the released binaries for node-canvas only support newer versions of macOS. On an older system, I have to run `npm install canvas --build-from-source` so that the transitive dependency [pixman](https://github.com/libpixman/pixman/) can load without crashing.

**Pull request merged**
