### PR TITLE
Add oneway arrows to remaining highway classes

### PR DESCRIPTION
**Pull request by claysmalley**
Adds oneway arrows to non-motorway highway classes, with half the layers.

Screenshot from 2022-07-24 19-39-28

### CODE REVIEW

**Comment by ZeLonewolf** [comment]
I honestly didn't even realize this was missing.

**Comment by ZeLonewolf** [comment]
It appears that this change also unifies the link and regular versions of each road class, is that also a deliberate consolidation?

**Comment by ZeLonewolf** [comment]
#513 would be helpful in assessing changes in layer count.

**Comment by claysmalley** [comment]
> It appears that this change also unifies the link and regular versions of each road class, is that also a deliberate consolidation?

Yes - were they separate layers intentionally?

**Comment by ZeLonewolf** [comment]
> Yes - were they separate layers intentionally?

Only in the sense that I (a) didn't really know what I was doing and (b) didn't realize layer count had a performance implication.

**Comment by ZeLonewolf** [comment]
The changes appear to be working from visual inspection.

The arrows on motorway_link are hard to see and we may want to open a separate issue to track it, as reducing layer count is a clear improvement by itself.

image

**Comment by claysmalley** [comment]
Adding oneway arrows seems to cause a significant slowdown at very high zoom, so it's hidden at ≥z20.

**Comment by ZeLonewolf** [comment]
> Adding oneway arrows seems to cause a significant slowdown at very high zoom

This sounds dodgy.

**Comment by jleedev** [comment]
_Something_ is extremely slow at high zooms already.

**Comment by claysmalley** [comment]
How about white arrows for motorways and trunks?

Screenshot from 2022-07-24 22-41-24

**Comment by claysmalley** [comment]
On second thought, white is even less legible against the red on trunk_link. Changing trunk oneway arrows back to black.

Screenshot from 2022-07-24 22-45-36

**Comment by ZeLonewolf** [comment]
There is an artifact in cases of a link road:

image
Location ([localhost link](http://localhost:1776/#17/41.513485/-71.367262))

Is this resolvable with a change in ordering or unavoidable?  Is there a way to prevent the arrows from being drawn too close to the ends of a road?

**Comment by claysmalley** [comment]
We would have to sandwich oneway arrows in between two road fill layers, which would hinder our ability to refactor roads to use more expressions and fewer layers. I don't think there's an easy solution to this.

**Comment by 1ec5** [comment]
> Is there a way to prevent the arrows from being drawn too close to the ends of a road?

It is possible to use invisible spacer symbols to collide out any arrows that would be drawn at the endpoints, similar to how we’re pushing waterway labels away from bridges. In this case, the symbol’s [`symbol-placement`](https://maplibre.org/maplibre-gl-js-docs/style-spec/layers/#layout-symbol-symbol-placement) property would be set to `point` so that it gets placed at one of the endpoints instead of repeated along the line. We’d need to pay attention to the spacing settings so that shields and road names don’t become less dense because of collisions suddenly occurring at junctions – or junctions on nearby roadways. Also, openmaptiles/planetiler-openmaptiles#10 proposes to fix wrong-way one-way arrows by disabling line merging of one-way lines; with that stopgap fix in place, the spacers would frequently prevent any one-way arrows or shields from showing up at all on one-way streets.

/ref mapbox/mapbox-gl-js#4003

**Comment by 1ec5** [comment]
One-way arrows only come in at z15 for freeways. At this zoom level, we’re already starting to show surface streets in the “cased” style. I think this gives us some flexibility to deemphasize color distinctions based on road classification. It’s also at a high enough zoom level that there’s a less ambiguity as to which ramp goes in which direction, so maybe the ramp arrows aren’t essential.

/ref #486

**Comment by claysmalley** [comment]
Oneway arrows removed from link roads:

Screenshot from 2022-08-30 20-54-39

**Comment by adamfranco** [comment]
Hmm... Without arrows on link roads, figuring out whether a ramp is an on or off requires the eye tracing it up to the lanes it diverges from. I imagine that there are a few cases of stacked interchanges where that becomes really difficult to tease out visually. (for example, the [GW bridge](https://zelonewolf.github.io/openstreetmap-americana/#17.49/40.849807/-73.941963))

**Comment by ZeLonewolf** [comment]
These looks pretty good for all but the lowest highway classes.

For the tiniest roads (alleys and so forth), I'm not sure if I'm seeing arrows or if there's a speck on my laptop screen that needs to be cleaned.  Not sure if there's a good solution to this.  Perhaps a hard minimum size to the arrow and let it overflow a bit?

[Location](https://preview.ourmap.us/pr/512/#map=17/41.490536/-71.31307):
image

Wondering if we might

**Comment by claysmalley** [comment]
This better?

image

**Comment by ZeLonewolf** [comment]
This looks good!

I note that bridges are not included ([example](https://preview.ourmap.us/pr/512/#map=15/41.52993/-71.40433)), however, bridges appear to be not supported presently. Is that intended to be part of this PR or left as future work?

**Comment by claysmalley** [comment]
> I note that bridges are not included ([example](https://preview.ourmap.us/pr/512/#map=15/41.52993/-71.40433)), however, bridges appear to be not supported presently. Is that intended to be part of this PR or left as future work?

That's a mistake. They're in the list of layers, so I don't know why they aren't showing up.

**Comment by claysmalley** [comment]
Figured it out. The culprit was the invisible spacer label that prevents waterway labels from colliding with bridges. This spacer is now disabled if the bridge is tagged `oneway=yes`.

[image](https://preview.ourmap.us/pr/512/#map=15.01/42.36907/-71.06575)

**Review by ZeLonewolf — APPROVED** [review]
Good work.  Thanks for sticking it out!
This would be a great use case for #881 if we're not in a rush to push the change.

**Comment by jleedev** [comment]
The arrows seem to serve the spacers' purpose except at _really_ high zooms.

Screenshot_20230621-123530

**Comment by claysmalley** [comment]
> The arrows seem to serve the spacers' purpose except at really high zooms.

Before removing the spacer, oneway arrows would _only_ show up at very high zooms. Something weird is going on and it's cooking my CPU.

**Comment by jleedev** [comment]
Ah, it might be that some combination of spacers + oneway arrows + lettering causes this.

I still also hypothesize that it's overzooming the z14 tile to z22 and then stuffing it full of symbols, i.e. if higher zoom tiles existed that were simply slices of the full ones then it would attempt to do less work.

Might also be that the waterway lettering is attempting to overlap itself severely, could see if the slowdown is localized depending on the presence of waterways or oneways.

https://osmus.slack.com/archives/C01V02K52UX/p1658777024337899

**Pull request merged**
