### PR TITLE
Generate maps of supported states, countries for shields

### PR DESCRIPTION
**Pull request by 1ec5**
Similar to #179, this PR adds a Node script that generates choropleth maps of the United States and world that show which states’ and countries’ shields are supported by OpenStreetMap Americana. The SVG maps are placed in the documentation folder, making it convenient to link to the GitHub repository in conversations about shield support. See this PR’s rich diff for the current output. The maps are based on public domain base maps of [U.S. states](https://commons.wikimedia.org/wiki/File:Blank_USA,_w_territories.svg) and [world countries](https://commons.wikimedia.org/wiki/File:World_map_configurable.svg) on Wikimedia Commons.

### CODE REVIEW

**Comment by ZeLonewolf** [comment]
Some states (notably, Maine and all of southern New England) have plain black rectangles with a white background for shields.  I consider these to be officially supported by the default symbology.  How should we handle those cases?  Should we explicitly declare those as default rectangles in the shield def?

**Comment by 1ec5** [comment]
I think we should declare them somewhere. That would also allow our support for them to show up in taginfo. One idea I had for #118 is to describe standard shields by their shape and color directly in the definition, instead of calling out to any function, then resolve those descriptions later. We could detect descriptions that happen to match the default and avoid drawing anything special for them.

**Comment by ZeLonewolf** [comment]
> describe standard shields by their shape and color directly in the definition, instead of calling out to any function

This is a pretty straightforward refactor.  I initially hadn't done this because we don't have a current use case for marshalling and unmarshalling the shield style.

**Comment by ZeLonewolf** [comment]
Looks good to me and seems to work.  What's the plan for doing something with these generated maps?  It isn't linked to any of the documentation files that I can see.

**Comment by 1ec5** [comment]
Before merging:

* [ ] Come up with a stopgap solution for shields that should be white rectangles, in anticipation of #118
* [ ] Embed the maps into a Markdown guide tracking the project’s progress on shields

**Review by ZeLonewolf — APPROVED** [review]
Looks essentially correct and javascript previously tested.  I'm not able to confirm that the  links deploy properly since that's done with github actions, so please check that the links are working after the merge.

**Comment by 1ec5** [comment]
> Looks essentially correct and javascript previously tested. I'm not able to confirm that the  links deploy properly since that's done with github actions, so please check that the links are working after the merge.

The links in this PR are confined to files that are excluded from the package distribution. They’re only intended to appear here on GitHub. The rich diff of this PR is representative of what visitors to this repository will see.

**Pull request merged**
