### PR TITLE
CI for building page

### LINKED ISSUE #37: Automatically deploy changes to gh-pages
When a commit is made to the main branch, it should trigger an update of the gh-pages branch (where the public map is hosted).

An example of how to do this is here, courtesy of @wipfli:
https://github.com/maplibre/maplibre-gl-js-docs/blob/main/.github/workflows/build-test-deploy.yml

### PR DESCRIPTION
**Pull request by akadouri**
Closes #37

See example run here: https://github.com/akadouri/openstreetmap-americana/actions/runs/1041454591
Will produce this output in `gh-pages`: https://github.com/akadouri/openstreetmap-americana/tree/gh-pages

This will make the link `https://zelonewolf.github.io/openstreetmap-americana/` since it uploads the `style` folder to the gh-pages branch.

### CODE REVIEW

**Comment by ZeLonewolf** [comment]
This all looks like magic to me, so I'll have to assume this wizardry work :)

**Comment by ZeLonewolf** [comment]
The automated check are blocking me from merging.  Error is:
```
Determining the checkout info
  /usr/bin/git branch --list --remote origin/build_page
  /usr/bin/git tag --list build_page
  Error: A branch or tag with the name 'build_page' could not be found
```

**Comment by akadouri** [comment]
Updated lint check, it won't try to update the code itself anymore because of PRs across separate forks.

Added a github banner as well so that folks can get to this repo if they stumble on the website as it gets shared, can drop it later when we add some more UI. -

Screen Shot 2021-07-18 at 12 05 47 PM

**Review by ZeLonewolf — APPROVED** [review]

**Comment by ZeLonewolf** [comment]
Thanks!

**Comment by zekefarwell** [comment]
Cool!  Thanks for setting this up, @akadouri.  Should we merge #36 now to test it?

**Pull request merged**
