### PR TITLE
Add shields for remaining New Jersey counties

### PR DESCRIPTION
**Pull request by claysmalley**
Adds support for Bergen, Cape May and Hunterdon Counties. Bergen County is unique in having white-on-black rectangular shields, identical to this project's default. Cape May and Hunterdon Counties use blue pentagons like the rest of New Jersey, but were previously missing from the definitions.

### CODE REVIEW

**Comment by ZeLonewolf** [comment]
On the original pass of this, I remember there being some discussion of underscores versus spaces in the network name for multi-word county names, are we satisfied that's resolved?

**Comment by claysmalley** [comment]
Wisconsin #260 and Florida #288 already solidified some inconsistent tagging in this regard. While everything seems consistent within each state we support, I could see the utility of harmonizing county road tagging nationwide. I guess it's now or never if we want county roads to follow a standard scheme.

**Comment by ZeLonewolf** [comment]
Off the top of my head, the more specific problem was inconsistent tagging for the same county network in NJ, and a difference in convention for different counties within NJ.  I think we had both `Cape May` and `Cape_May` when we first looked at it.

**Comment by claysmalley** [comment]
70 relations have `network=US:NJ:Cape_May`, and only one has `network=US:NJ:Cape May`. Looks like the underscore is heavily preferred here.

**Comment by ZeLonewolf** [comment]
Cool, sounds like underscore is the winner then.

**Review by ZeLonewolf — APPROVED** [review]
Seems straightforward to me!

**Pull request merged**
