### PR TITLE
Fix banner drop shadow overlapping shield

### PR DESCRIPTION
**Pull request by ZeLonewolf**
This PR fixes the issue we have with banner text drop shadows obscuring the top of a shield.  In addition, this removes the kludge we were using to draw a glow effect and replaces it with an actual glow effect using a text stroke with blur.

**Before**
image

**After**
image

### CODE REVIEW

**Comment by claysmalley** [comment]
Would it be easy to scoot the banners up a pixel or two? Right now they're a little close to the shields:
Screenshot from 2022-05-20 22-51-20

**Comment by ZeLonewolf** [comment]
Sure.  The cheap way is to just increase the banner height:

image

I'll play with a fix to insert an actual gap.

**Comment by ZeLonewolf** [comment]
Why yes, that is satisfying now that you mention it:

image

**Comment by claysmalley** [comment]
I'm not seeing any change when there's a single banner:
Screenshot from 2022-05-21 08-54-29

The presence of banners on one shield noticeably scoots nearby shields down with it. This bug is present in `main`. If it's not fixable in this PR, let's open a new issue for it:
Screenshot from 2022-05-21 08-54-09

**Comment by claysmalley** [comment]
Never mind, I just had to clear my cache. Looks much better!
Screenshot from 2022-05-21 12-01-24

The unbannered shields being too far down is still an issue though.
Screenshot from 2022-05-21 12-03-13

**Comment by ZeLonewolf** [comment]
> The unbannered shields being too far down is still an issue though.

That one isn't easily solvable.  It would require a change to maplibre to adjust the baseline for shields, or some other pixel gymnastics that I haven't thought of yet.

**Review by claysmalley — APPROVED** [review]
Looks good.

Banner issue tracked in #340.

**Pull request merged**
