### PR TITLE
Replace Makefile with npm scripts

### LINKED ISSUE #134: Replace Make targets with NPM scripts
We’re already using NPM for package management, so using it also for the build system would simplify the development environment, especially for Windows users who may not have `make` installed. Each of the Make targets can be replaced by a `script` in the package.json file, so developers can run for instance `npm run code_format`.

### PR DESCRIPTION
**Pull request by adamfranco**
This PR fixes #134, replacing the Makefile with npm scripts defined in the `package.json`.

I'm submitting this PR as a stand-alone without further changes to the build process. As noted in #135, it will likely be useful with either [Parcel](https://parceljs.org/) (what I've used for my projects), or [WebPack](https://webpack.js.org/) to minify the JS, combine CSS, and resolve paths to dependencies in node_modules. I'll submit a separate PR that builds on this one and uses parcel to do the bundle/build. In the event that WebPack is preferred or a different build process is desired, this PR can be used alone.

### CODE REVIEW

**Review by ZeLonewolf — COMMENTED** [review]
This looks good to me.  I would like @Mashin6 to review also to confirm that this all works as expected on Mac.

**Comment by adamfranco** [comment]
More review is welcome. I'm pretty new to npm myself and am sure there are more canonical ways of doing things than I came up with (such as calling scripts from scripts without just chaining them in a shell with `&&` 🤷 ).

FWIW I'm put this together on an x64 Mac running Catalina and have tested on an m1 Mac running Big Sur after going the steps in [#132](https://github.com/ZeLonewolf/openstreetmap-americana/issues/132#issuecomment-1028271663).

**Comment by zekefarwell** [comment]
This project was the the first time I encountered a Makefile in a web development project.  I think it was something @akadouri set up early on.  I thought it was a bit weird at first and wondered why we weren't just using npm scripts, which I was more familiar with.  However, since then I've come to appreciate the flexibility of the Makefile syntax and I've switched over a couple other projects to using Makefiles instead of npm scripts.  I can't say I see what the need to make this change really is, but if everyone else is on board it's fine with me.  I'm comfortable with either tool.

**Comment by Mashin6** [comment]
I managed to run it on my arm64 Mac fine. I can't comment on the code itself since I know nothing about javascript or node.js

**Comment by akadouri** [comment]
Those were quite the early days @zekefarwell. I didn't really have any specific reason for going that way instead of npm scripts, at work we stick to Makefiles for consistency across projects no matter the language/framework. The important thing is making sure commands people need are committed and easy enough to find.

**Review by Mashin6 — APPROVED** [review]

**Comment by ZeLonewolf** [comment]
Looks good!

**Pull request merged**
