### PR TITLE
Add Bookstores

### PR DESCRIPTION
**Pull request by wmisener**
Based on the discussion in #1014, I'm reusing the upright book icon added for libraries but in "consumer orange" for bookstores (`shop=books` in OSM, class `library` + subclass `books` in OMT). They appear at z16, the same as similar consumer POIs like coffee shops, bars, car repair shops, etc.

Screen Shot 2024-02-17 at 10 02 48 PM

Screen Shot 2024-02-17 at 10 10 34 PM

Screen Shot 2024-02-17 at 10 12 16 PM

Screen Shot 2024-02-17 at 10 13 19 PM

### CODE REVIEW

**Comment by ZeLonewolf** [comment]
Did you intend to modify icons/shield_us_az_scenic.svg with this PR?

**Comment by wmisener** [comment]
> Did you intend to modify icons/shield_us_az_scenic.svg with this PR?

Oops, no. I think running code_format might've picked it up? It doesn't look like a material change to the icon

**Comment by adamfranco** [comment]
I think this looks good, but I wonder if we should worry about accessibility for various types of color blindness? These colors might not be an issue, or maybe the presence of labels is enough, but just thought I should flag this before we make too many identical icons in different categories.

**Comment by ZeLonewolf** [comment]
> accessibility for various types of color blindness?

It strikes me that one of the things we could implement (since this a vector style, after all) is the ability to toggle various color blindness settings that could change the colors en masse on the fly (in a similar vein to what we do with label language.

If different colors that mean different things aren't color-blind discernible, we probably shouldn't rely on differentiated icons to paper over that.

**Comment by wmisener** [comment]
> I think this looks good, but I wonder if we should worry about accessibility for various types of color blindness? These colors might not be an issue, or maybe the presence of labels is enough, but just thought I should flag this before we make too many identical icons in different categories.

Thanks for raising this. Using the nifty tool here: https://davidmathlogic.com/colorblind/#%23F38F00-%23003F87-%23693F23-%23A20067-%234E008E-%23006747 with our current POI colors: 
Screen Shot 2024-02-18 at 11 11 32 AM

This seems to indicate that orange and blue are essentially always distinguishable. The purple (used for airport features) tends to look blue, while mauve (used for transport features) can look similar to either brown or blue depending on the type of color-blindness (the first two are more common than the third).

Based on this, it might be worth considering changing the shade of blue and/or purple we use. If we implement green icons, care will be needed to make sure they don't look identical to our brown icons. Otherwise, as Brian suggests, we could implement on-the-fly color switching, or clickable icons that display more information (I could imagine a subtitle under the name with the legend entry, for example). But these accessibility considerations might merit their own issue for further discussion.

I still think with some care, we can make distinguishable colors, and the benefits that reusing icons has for style coherence outweigh the downsides of potential confusion.

**Review by claysmalley — APPROVED** [review]
Looks good to me.

Let's put tail work about colorblind analysis into a new issue.

**Comment by ZeLonewolf** [comment]
Thanks for working this, forked off the CVD work to #1038.

**Pull request merged**
