### PR TITLE
Adjust padding of US Interstate shield

### PR DESCRIPTION
**Pull request by claysmalley**
Adjusts the padding of US Interstate shields to prevent 3-digit routes from being shown on the 2-digit shield variant.
Screenshot from 2022-06-05 21-06-00 Screenshot from 2022-06-05 21-06-16
Screenshot from 2022-06-05 21-06-34 Screenshot from 2022-06-05 21-06-53

### CODE REVIEW

**Comment by ZeLonewolf** [comment]
The screen shots look great, is there any possibility that the change in #369 will interact with this somehow?

**Comment by claysmalley** [comment]
Interstate 5 has slightly smaller text but nothing else is changed.
Screenshot from 2022-06-06 14-10-32

**Comment by ZeLonewolf** [comment]
On my display, I'm seeing the numbers run into the crown:
image

**Comment by claysmalley** [comment]
How's this?
Screenshot from 2022-06-06 14-35-11
Screenshot from 2022-06-06 14-35-28

**Comment by claysmalley** [comment]
I think the gap is forgivable in my screenshots. I have no idea what's causing the rendering discrepancy.

**Review by ZeLonewolf — APPROVED** [review]

**Pull request merged**
