### PR TITLE
Use pre-built maplibre

### PR DESCRIPTION
**Pull request by ZeLonewolf**
I've posted a pre-built development version of maplibre in gh-pages.  This PR eliminates the need to build maplibre and instead just points index.html to that location.  I used the fully-qualified URL so that it would work in a development context as well.

### CODE REVIEW

**Comment by jleedev** [comment]
How does this jive with the action in https://github.com/ZeLonewolf/openstreetmap-americana/blob/main/.github/workflows/deploy.yml?

I think you need to e.g. fork maplibre-gl-js and push to gh-pages branch there, so it doesn't get clobbered.

**Comment by jleedev** [comment]
Oh, I understand, you're not going to merge your large PR and deploy to gh-pages until such time as maplibre-gl-js has been merged and deployed to npm. So you're just staging this js file there in the meantime.

**Comment by jleedev** [comment]
So are you supposed to be merging into main or openmaptilers-new-features-test?

**Comment by ZeLonewolf** [comment]
I was going to merge the pointer to pre-built mapLibre to main and change the pointers to get mapLibre hosted.  Then I plan to change the big branch to point to that mapLibre also.  We can still merge the big shield branch to main before the new mapLibre is out - that branch is help up waiting for MapTiler Cloud.  Hope this made sense.

**Review by jleedev — APPROVED** [review]

**Pull request merged**
