### PR TITLE
add Weld County Parkway shield

### LINKED ISSUE #988: Weld County Colorado Shields
There are signed county routes in Weld County, CO (`US:CO:Weld`), and in an additional peculiarity, the Weld County Parkway (composed of part of CR 47 and CR 49) has its own design style (https://www.weld.gov/Government/Departments/Public-Works/Transportation-Planning/Access-Control-Plans/WCR-49-ACP, https://www.weld.gov/Government/Departments/Public-Works/Transportation-Planning/Access-Control-Plans/WCR-47-ACP, matches the field signage pretty closely) (`US:CO:Weld:WCP`).

### PR DESCRIPTION
**Pull request by claysmalley**
Fixes #988.

image

### CODE REVIEW

**Comment by ZeLonewolf** [comment]
Graphic:

image

**Comment by ZeLonewolf** [comment]
I did some cruising on Google Maps and I was unable to find any evidence of the purple shields in use.  Of note, these are largely dirt roads to very rural areas:
image
image
image

**Review by ZeLonewolf — APPROVED** [review]
The purple signs appear to be new.  On that basis, I'm good with moving forward with these.

image

**Comment by ZeLonewolf** [comment]
It might be the lighting but in the photo it looks more blue than purple.

**Comment by claysmalley** [comment]
I looked at the signage examples I found earlier, and they do appear to be more blue than purple, despite the image on the county's website. I went ahead and changed it. It's pretty hard to distinguish contrasted against green.

image

**Pull request merged**
