### PR TITLE
Add Maryland shields

### PR DESCRIPTION
**Pull request by claysmalley**
Adds shields for Maryland. This state has highway shields shaped like ~a can of Old Bay~ a simple rectangle with a tall top border. I removed the state name but retained the black stroke across the top, a compromise often seen on guide signs.

Business routes in Maryland are signed with green shields, both on state highways and US highways. This PR only colors business state highways green.

Screenshot from 2022-04-21 17-15-03 Screenshot from 2022-04-21 17-15-25
MD_Route_97
MD_Route_313

### CODE REVIEW

**Comment by mretoolforge** [comment]
I have a suggestion for Maryland that I was actually about to make an issue about - the map should not render route shields at all in Baltimore City, except for I-83 (the Jones Falls Expressway) and Route 40 (Franklin Mulberry Expressway). And for both of those, the shield shouldn't appear before their actual name appears. All roads in the city, including those that are nominally highways, are also not maintained by the Maryland State Highway Administration and none of them besides have I-83 and possible Route 40 have posted numbers as far as I'm aware. The way the map is at the moment is it fills Baltimore with numbers and symbols almost nobody in Baltimore has ever heard of, and obscures the distinctions between corridors that people are familiar with. For example, few would know Druid Hill Avenue has a number (129 apparently) and Pennsylvania Avenue is considered the major corridor in that region. Likewise, Fulton Avenue is labeled Route 1 despite running through a part of the city where the majority of the population does not have a driver's license (and shares a number with other streets which are not similar to it).

At some point I want to try putting in a pull request of some signage specific/unique to Baltimore to use instead. For example, most would recognize the light rail and metro subway signage (which are in the MD MUTCD book), even drivers, as they relate to major landmarks, and both systems share the road with cars along part of their length. I'm not sure if this would be seen as a joke and/or introduce copyright issues, but official reports on the one actual highway we have (I-83) refer to a stretch of it by the "Pepsi sign" because 83 famously doesn't have mile markers on it, or at least visible ones - it would legitimately make the map easier to understand for locals and visitors alike (See https://www.baltimoresun.com/maryland/baltimore-city/bs-md-ci-pepsi-sign-crashes-20170123-story.html).

**Comment by claysmalley** [comment]
> I have a suggestion for Maryland that I was actually about to make an issue about - the map should not render route shields at all in Baltimore City, except for I-83 (the Jones Falls Expressway) and Route 40 (Franklin Mulberry Expressway). And for both of those, the shield shouldn't appear before their actual name appears. All roads in the city, including those that are nominally highways, are also not maintained by the Maryland State Highway Administration and none of them besides have I-83 and possible Route 40 have posted numbers as far as I'm aware.

This is a problem solvable by tagging on OpenStreetMap. If it's truly the case that these routes are unsigned within Baltimore city limits, the underlying `route=road` relations can be split into segments for the signed and unsigned portions of the routes, and the relations for the unsigned portions would have `unsigned_ref=*` instead of `ref=*`. This would ensure that shields won't render on the unsigned portions.

**Comment by HY-TBN** [comment]
Alright, they should definitely be tagged that way then. For reference, I found some good examples of common patterns in maps that people in Maryland are familiar with since I've seen people post similar on other issues:

Maryland state provided maps often just do not even show highways in Baltimore even if they are shown elsewhere: https://msa.maryland.gov/megafile/msa/speccol/sc5300/sc5339/000113/015000/015332/unrestricted/20121168e.pdf

The city has what it calls "city gateways" which are mostly signed and match the major corridors of the city (not sure if any of these are tagged on OSM): https://transportation.baltimorecity.gov/sites/default/files/City%20Gateway%2011x17.pdf

A common pattern you see on city maps is that if a highway shield besides 83 is shown, it is only shown in industrial zones within city limits where I think they are posted for the benefit of truck drivers. The above map has this, and you can see it on transit maps: https://s3.amazonaws.com/mta-website-staging/mta-website-staging/files/System%20Maps/Geographic_System_Map_11_2021.pdf

You can also see that the route number on the above is replaced with the actual name wherever the actual name is the one people use, for example "US-40" becomes "Edmondson" in far West Baltimore even though it is technically the same number and road name on both sides of the city line.

Most maps of the city feature railways with a thicker line/more prominent color. Even this map, which was designed by the State Highway Administration to emphasize roads which have highway route numbers but no posted signs, does this: https://www.roads.maryland.gov/Town_Gridmaps/100000_BaltimoreCity.pdf

**Comment by mretoolforge** [comment]
Alright, they should definitely be tagged that way then. For reference, I found some good examples of common patterns in maps that people in Maryland are familiar with since I've seen people post similar on other issues:

Maryland state provided maps often just do not even show highways in Baltimore even if they are shown elsewhere: https://msa.maryland.gov/megafile/msa/speccol/sc5300/sc5339/000113/015000/015332/unrestricted/20121168e.pdf

The city has what it calls "city gateways" which are mostly signed and match the major corridors of the city (not sure if any of these are tagged on OSM): https://transportation.baltimorecity.gov/sites/default/files/City%20Gateway%2011x17.pdf

A common pattern you see on city maps is that if a highway shield besides 83 is shown, it is only shown in industrial zones within city limits where I think they are posted for the benefit of truck drivers. The above map has this, and you can see it on transit maps: https://s3.amazonaws.com/mta-website-staging/mta-website-staging/files/System%20Maps/Geographic_System_Map_11_2021.pdf

You can also see that the route number on the above is replaced with the actual name wherever the actual name is the one people use, for example "US-40" becomes "Edmondson" in far West Baltimore even though it is technically the same number and road name on both sides of the city line.

Most maps of the city feature railways with a thicker line/more prominent color. Even this map, which was designed by the State Highway Administration to emphasize roads which have highway route numbers but no posted signs, does this: https://www.roads.maryland.gov/Town_Gridmaps/100000_BaltimoreCity.pdf

**Comment by 1ec5** [comment]
There are a lot of interesting ideas here, but I’m not sure how much of them can be implemented in the scope of this PR, which just fixes the appearance of the existing route shields to look less like Connecticut’s or Indiana’s. Some of suggestions here may require changes to OpenMapTiles or Planetiler in addition to changes in the OSM database. @mretoolforge, would you mind opening a separate issue summarizing the changes you think would make the renderer more usable to Baltimoreans? Thanks!

**Comment by mretoolforge** [comment]
For sure, I was thinking of doing that but I saw Maryland and got distracted

**Comment by 1ec5** [comment]
Continuing the discussion about optimizing for Baltimore and other urban areas in #299.

**Review by 1ec5 — APPROVED** [review]

**Pull request merged**
