### PR TITLE
Add Zia sun symbol for New Mexico shield

### PR DESCRIPTION
**Pull request by claysmalley**
Changes the shields of Iowa, Kentucky, New Mexico and Virginia (secondary) to use `circleShield()` instead of `roundedRectShield()`. I intentionally left this out of the previous PR because it's a stylistic choice and it'd need more discussion.  

For shields that are circle-shaped for 1 or 2 digits, behavior is different when expanding to 3 or more digits. Delaware, Mississippi and New Jersey use an oval. Kentucky uses a geometric stadium. Iowa, New Mexico, and the secondaries of Virginia maintain a circle and compress the text, though they have been assigned stadium shapes in this project.

In my opinion, this distinction is not worth keeping. All of these networks are just as recognizable if we stick to one shape for shields with 3 or more digits. I think ovals look better than stadiums for these cases.

(Note that this does not change `network=CA:ON:private_toll`, which would be unrecognizable without the stadium shape, and is probably a good candidate for an SVG shield anyway.)

before:
Screenshot from 2022-05-14 14-33-04 Screenshot from 2022-05-14 14-32-49

after:
Screenshot from 2022-05-14 14-32-14 Screenshot from 2022-05-14 14-32-28

before:
Screenshot from 2022-05-14 14-34-09 Screenshot from 2022-05-14 14-34-21

after:
Screenshot from 2022-05-14 14-34-58 Screenshot from 2022-05-14 14-34-46

### CODE REVIEW

**Comment by 1ec5** [comment]
We also considered standardizing all of the rounded shields on “elongated circles” (what you’re calling a “stadium”), but I guess we ended up implementing a mix for some reason. Either shape is recognizable to Kentuckians, but the ovals are more common on maps that don’t display state-specific shields.

If we ever get around to addressing issues like rectangular shields looking far too big compared to custom shields, then the rounded rectangle and oval shields will also be impacted. Even among maps that apply a generic state route shield, ovals tend to be less compact. That said, the current rounded rectangle implementation doesn’t represent the elongated circle faithfully, because the corner radius isn’t large enough.

**Comment by claysmalley** [comment]
Using a 9px radius instead looks a lot more circley. Though we still have issues with clipping (#301), and at 100% zoom, there's a lot of extra whitespace around the numeral.

Screenshot from 2022-05-14 16-44-30 Screenshot from 2022-05-14 16-44-43

**Comment by zekefarwell** [comment]
> In my opinion, this distinction is not worth keeping. All of these networks are just as recognizable if we stick to one shape for shields with 3 or more digits. I think ovals look better than stadiums for these cases.

I was arguing the same "standarize on one shape" line in #117 back in January, though I was pushing for elongated circles at the time.  However, with many shield designs moving closer to the real world signs and farther from abstract representation, I suppose I'm perfectly happy to see the slight distinction between ovals and elongated circles matching real world usage.  This is a map style by and for road geeks after all.

**Comment by claysmalley** [comment]
> I'm perfectly happy to see the slight distinction between ovals and elongated circles matching real world usage. This is a map style by and for road geeks after all.

Good point. I'm okay with keeping this distinction, though this still leaves one question. Which design should we use for circles that _don't_ expand for 3 digits? It looks like geometric stadiums were agreed upon for Iowa, New Mexico and secondary Virginia, but I introduced ovals for the Virgin Islands in #250. Whatever we decide upon, I just want to make sure it's consistent.

**Comment by zekefarwell** [comment]
> Which design should we use for circles that _don't_ expand for 3 digits?

There are states that just cram a 3 digit number into a circle? 😱Heathens!  I _think_ we can all agree that deviating from real world shields in these cases with a wide variant is a good idea.  Bit of a toss up, but I guess I'd say go with the geometric stadiums/elongated circles.  What do others think?

**Comment by 1ec5** [comment]
Either way, West Virginia county routes will need some special attention once we get around to fixing #13:

[oval elongated circle](https://zelonewolf.github.io/openstreetmap-americana/#17/37.363296/-81.055772)

**Comment by claysmalley** [comment]
Shields originally stadium-shaped now have 9px corners as demonstrated above, and New Mexico has a new stadium-shaped Zia symbol:

Screenshot from 2022-05-14 20-11-52 Screenshot from 2022-05-14 20-12-05

**Comment by claysmalley** [comment]
American road atlases seem to heavily prefer geometric stadiums over ellipses, so I guess it makes sense to go with that. Though for the record, one state crams _four_ digits inside a Zia symbol inside a circle:

**Comment by 1ec5** [comment]
The two NMDOT maps I have are no help: one stuffs three digits into a circle, while the other crams three digits into a Zia symbol.

NMDOT 2010 NMDOT 2010 compact

**Comment by ZeLonewolf** [comment]
The Zia spikes seem to blend in with the backdrop a bit, do they need some kind of halo?

**Comment by claysmalley** [comment]
Would we be applying a halo to the whole shield, or just the spikes? Either way, it'd be the first shield with a halo effect, and I worry it wouldn't look good in context.

**Comment by zekefarwell** [comment]
Shields with light text on a dark background, like the interstate shields, have halos.  It definitely helps them stand out better when they have low contrast with objects below.  This one would be the first dark text on light background with a halo.  Seems worth seeing what it would look like at least.

**Comment by ZeLonewolf** [comment]
We don't have many shields that are red on the outside.  Offhand maybe one of the Yukon ones, but they barely have roads to conflict with up there 😂.  To me, the red outline has a not-great contrast with charcoal or red roads.  Though I acknowledge that this is probably also a problem on the existing map.

**Comment by claysmalley** [comment]
Demo with white halo:

Screenshot from 2022-05-16 17-06-18
Screenshot from 2022-05-16 17-06-05

**Comment by ZeLonewolf** [comment]
I think this looks good!

**Comment by claysmalley** [comment]
A cursory internet search indicates that the Zia Pueblo cares a lot about the usage of this symbol by non-natives ([see PDF](https://www.nmlegis.gov/handouts/IAC%20092914%20Item%206%20FINAL%20REPORT%20Zia%20Sun%20Symbol%20ekm%209%2029%202014.pdf)). While they don't own a trademark over the symbol, they do request that others ask for their permission before using it.

I can't find anything that says the New Mexico Department of Transportation's usage of the Zia symbol on highway shields is respectfully permitted. I'm hesitant to assume that the Zia symbol on highway shields is condoned, and regardless, I'd still like to ask permission before incorporating it into a new project.

I'll do some research on who to ask and how.

**Comment by ZeLonewolf** [comment]
Need to resolve conflicts

**Comment by claysmalley** [comment]
Here's an email to the Zia Pueblo I've got drafted:


> Hello,
> 
> I'm writing on behalf of the OpenStreetMap (OSM) community in the United States, as well as the maintainer team of OSM-Americana. OSM [1] is a freely editable online map run by a nonprofit organization (comparable to Wikipedia, but for maps), and OSM-Americana [2] is a map style being built by a team of mostly US-based volunteer mappers.
> 
> [1] https://www.openstreetmap.org/#map=12/35.4938/-106.7318
> [2] https://zelonewolf.github.io/openstreetmap-americana/#13.35/35.50421/-106.7224
>
> We've chosen to emulate a road atlas style familiar to a US audience for OSM-Americana, and we attempt to display route shields similar to their real-life appearance, where other OSM styles just put the route number in a rectangle. In the examples given above, OSM shows "US 550" in a rectangle, but OSM-Americana has "550" inside the actual white badge shape you'd see on the road. We'd like to have recognizable shields on state routes as well, including New Mexico.
>
> Of course, the Zia sun symbol is used on state route shields in New Mexico. While researching these shields, we found out about the cultural significance of this symbol, but we couldn't find anything saying the New Mexico Department of Transportation's decision to use it had any input from the Zia Pueblo. And if NMDOT never sought permission to use the symbol, it wouldn't be right for us to decide to use it. So, to clarify, we have a few questions:
>
> 1. Was the Zia Pueblo ever consulted when the New Mexico Department of Transportation decided to use the sun symbol for state route shields? Are there any problems with NMDOT's usage of the symbol?
>
> 2. If NMDOT's usage of the sun symbol on state route shields is acceptable, is it okay for us to use it in OSM-Americana to represent New Mexico state routes? Are there any considerations about the dimensions and position of the circle and the 16 rays?
>
> Regards,
> Clay Smalley


Thoughts, additions, objections?

**Comment by 1ec5** [comment]
Since you’re linking to the demo page, consider emphasizing that it’s still a work in progress. After all, this style isn’t showing any [reservation boundaries](https://www.openstreetmap.org/relation/9435182) yet: #105.

**Comment by claysmalley** [comment]
Replacing the paragraph after the links: 

> Note that OSM-Americana is a work in progress. In the examples given above, aboriginal land boundaries (as a global concept, including, but not limited to, Indian Reservations in the US) are shown on OSM, but we are still working on adding support for them in OSM-Americana, and we hope to have them on the map before we publicly release it.
>
> We've chosen to emulate a road atlas style familiar to a US audience for OSM-Americana, and we attempt to display route shields similar to their real-life appearance where other OSM styles just put the route number in a rectangle. For example, OSM shows "US 550" in a rectangle, but OSM-Americana has "550" inside the actual white badge shape you'd see on the road. We'd like to have recognizable shields on state routes as well, including New Mexico.

**Comment by claysmalley** [comment]
Here's the final version I sent:

> Hello,
>
> I'm writing on behalf of the OpenStreetMap (OSM) community in the United States, as well as the maintainer team of OSM-Americana. OSM [1] is a freely editable online map run by a nonprofit organization (comparable to Wikipedia, but for maps), and OSM-Americana [2] is a map style based on OSM being built by a team of mostly US-based volunteer mappers. We'd like to know more about the Zia Pueblo's perspective on the usage of the sun symbol on New Mexico state route signage, and whether it's appropriate for us to replicate that signage in OSM-Americana.
>
> [1] https://www.openstreetmap.org/#map=12/35.4938/-106.7318
> [2] https://zelonewolf.github.io/openstreetmap-americana/#13.35/35.50421/-106.7224
>
> Note that OSM-Americana is a work in progress. In the examples given above, aboriginal land boundaries (as a global concept, including, but not limited to, Indian Reservations in the US) are shown on OSM, but we are still working on adding support for them in OSM-Americana, and we hope to have them on the map before we publicly release it.
>
> We've chosen to emulate a road atlas style familiar to a US audience for OSM-Americana, and we attempt to display route shields similar to their real-life appearance where other OSM styles just put the route number in a rectangle. For example, OSM shows "US 550" in a rectangle, but OSM-Americana has "550" inside the actual white badge shape you'd see on the road. We'd like to have recognizable shields on state routes as well, including those in New Mexico (currently represented by a red circle).
>
> Of course, the Zia sun symbol is used on state route shields in New Mexico. While researching these shields, we found out about the cultural significance of this symbol, but we couldn't find anything saying the New Mexico Department of Transportation's decision to use it had any input from the Zia Pueblo. And if NMDOT never sought permission to use the symbol, it wouldn't be appropriate for us to perpetuate such a mistake. So, to clarify, we have a few questions:
>
> 1. Was the Zia Pueblo ever consulted when the New Mexico Department of Transportation decided to use the sun symbol for state route shields? Are there any problems with NMDOT's usage of the symbol?
>
> 2. If NMDOT's usage of the sun symbol on state route shields is acceptable, would it be okay for us to use it similarly in OSM-Americana to represent New Mexico state routes? Are there any rules or guidelines about the size and position of the circle and the 16 rays?
>
> Thank you for your time and consideration.
>
> Regards,
> Clay Smalley

**Comment by ZeLonewolf** [comment]
How long should we wait for a response?

**Comment by ZeLonewolf** [comment]
I'm comfortable with the email reach-out being sufficient and following NMDOT's lead if you want to proceed with this.

**Comment by claysmalley** [comment]
I re-sent the email. If I don't get a response in a week or so, I'll try calling them. Failing that, I'll close this PR—I think it's important for us to be certain that NMDOT is using this symbol with respect and permission before replicating it on a digital map.

**Comment by ZeLonewolf** [comment]
There seems to be a request form here:

https://static1.squarespace.com/static/5cd0597b0cf57d0b7478c56a/t/657b6196a2e8a0581e072e64/1702584726764/Zia+Sun+Symbol+Request+Form+PDF+2023.pdf

It is linked from this page: https://www.ziapueblo.org/

**Comment by claysmalley** [comment]
I've resent the email to info@ziapueblo.org, with the form and a few example screenshots attached.

**Comment by claysmalley** [comment]
Good news! The Zia Pueblo has generously granted us permission to use the Sun Symbol. Full response (with personal info and payment details redacted):

> April 29, 2024
> 
> Clay Smalley
> OpenStreetMap Americana
> 
> Dear Mr. Smalley,
> 
> On behalf of the Pueblo of Zia, we hereby grant you permission to use our most sacred Zia Sun Symbol, as you had requested for business to create digital maps. I would also like to take this opportunity to express my appreciation for your generous donation of $50.00 to the Pueblo of Zia Scholarship Fund.
> 
> I would also like to thank you for taking the time to reach out to the Pueblo of Zia, to request permission for the use of our Zia Sun Symbol.
> 
> Sincerely,
> 
> Delbert Pino
> Lt. Governor
> Pueblo of Zia

I'll just need to resolve some conflicts, and this PR will be ready.

**Review by ZeLonewolf — APPROVED** [review]
Looks great!

image

image

**Pull request merged**
