### PR TITLE
update package-lock.json

### PR DESCRIPTION
**Pull request by claysmalley**

### CODE REVIEW

**Comment by jleedev** [comment]
Obviously this sort of nonsense should be automated, since the build uses `npm ci` it requires that the package-lock periodically be updated to pick up fixes, but can you clarify what's going on here?

**Comment by ZeLonewolf** [comment]
As a general solution, perhaps we could add to the lint job to also check to see if the package-lock.json is stale?

**Comment by wolfy1339** [comment]
I suggest taking a look at
https://github.com/apps/renovate

**Review by ZeLonewolf — APPROVED** [review]

**Comment by jleedev** [comment]
In fact, `npm update` seems to be wildly unstable, or has been changed in different versions of `npm`, and I really don't care about this, except:

- Having a checked-in package lock is understood to be a good thing, so that `npm ci` will produce (hopefully) consistent results, and
- Something (either an annoying github bot, or the chaotic forces of developers running `npm install`) should periodically update the transitive and semver-compatible dependencies.

**Comment by 1ec5** [comment]
> an annoying github bot

Also known as @dependabot…

**Pull request merged**
