### PR TITLE
Add Mass Pike shield

### PR DESCRIPTION
**Pull request by ZeLonewolf**
Add the Mass Pike shield for `network=US:MA:Turnpike`.

image

Artwork could be better, but I had a hard time finding a public-domain compatible shield to start from.
image

### CODE REVIEW

**Comment by claysmalley** [comment]
The background square has nonstandard dimensions, outline width and corner radius. Try copying an existing SVG with a rectangle background, and adding the hat icon on top.

**Comment by ZeLonewolf** [comment]
Icon update:

image

**Comment by claysmalley** [comment]
Not particularly fond of the pixelated version. The outer edges of the hat are mostly diagonal or curved, so the belt looks out of place with no pixel blending, especially when the map is tilted.

I tried my hand at a shield icon. The width is shrunk to 19px to center the buckle on pixel boundaries (also alluding to the actual portrait-oriented shield).

shield_us_ma_pike

**Comment by ZeLonewolf** [comment]
This version looks awesome!  Thanks for cleaning up my hamfisted attempts on this one.

image

**Review by claysmalley — APPROVED** [review]
Looks good!

**Pull request merged**
