### PR TITLE
Change shield definitions for county and city highway networks

### PR DESCRIPTION
**Pull request by claysmalley**
Changes definitions of currently supported county networks, and adds new ones, based on the [local highway network tagging guidelines.](https://wiki.openstreetmap.org/wiki/Proposed_features/County,_city_and_local_highway_networks_in_the_United_States)

Todo:
- [x] wait for voting to end on proposal (2022-06-08)
- [x] add county park access roads for Minnesota
- [x] check Louisiana for parish route networks
- [x] check Tennessee for county route networks
- [x] should anything in Ohio change? @1ec5

### CODE REVIEW

**Comment by claysmalley** [comment]
Green, Blue and Purple Belts no longer have a black stroke around the circle:

Screenshot from 2022-06-01 21-10-37
Screenshot from 2022-06-01 21-10-59

**Comment by 1ec5** [comment]
> should anything in Ohio change?

Not that I’m aware of, unless another township or three have decided to come up with their own nonstandard design in the time it takes me to write this. 😅

**Comment by claysmalley** [comment]
The retagging on OSM has been completed. Once this PR is merged, a data update (cc @ZeLonewolf) will make all the newly supported networks show up.

**Comment by claysmalley** [comment]
Fixes #142, fixes #270.

**Comment by ZeLonewolf** [comment]
Planet has been updated!

**Comment by claysmalley** [comment]
Looks as expected:
Screenshot from 2022-06-09 09-07-13 Screenshot from 2022-06-09 09-01-15 Screenshot from 2022-06-09 09-01-49

**Review by ZeLonewolf — APPROVED** [review]
Seems to be working as far as I can tell.  Some of these networks are nascent or aren't tagged yet, but they reflect an approved proposal so I think we're good to add render support _a priori_.

**Pull request merged**
