### PR TITLE
Add Lake Pontchartrain Causeway shield

### LINKED ISSUE #734: Lake Pontchartrain Causeway shield
Like many toll roads, the Lake Pontchartrain Causeway has a logo. Most signage directing drivers to the bridge just spell out its name, but the logo appears on tenth-mile markers along the bridge, in the same space normally reserved for a route shield. It’s pretty difficult to get the bridge’s long label to appear at any zoom level, so a more compact shield would improve usability.

[Guide sign](https://www.mapillary.com/app/?pKey=140815474641469)

[Entrance](https://commons.wikimedia.org/wiki/File:Lake_Pontchartrain_Causeway_-_Northbound_Entrance_%2828409132647%29.jpg)

[Distance marker](https://commons.wikimedia.org/wiki/File:Lake_Pontchatrain_Causeway_-_MM_11.9_-_Halfway_Point_%2842560009184%29.jpg)

After simplifying for a size of 20×20 pixels, the official logo would be too simple to be eligible for copyright protection:

[Logo](https://thecauseway.us/wp-content/uploads/2021/10/GNOEC-Logo_Small_300-e1645807872566.png)

### PR DESCRIPTION
**Pull request by 1ec5**
Added a shield for the Lake Pontchartrain Causeway.

[Mandeville](https://zelonewolf.github.io/openstreetmap-americana/#map=10/30.3813/-90.0704) [Crossover](https://zelonewolf.github.io/openstreetmap-americana/#map=18/30.142523/-90.132655/45/40)

Fixes #734.

### CODE REVIEW

**Review by ZeLonewolf — COMMENTED** [review]
Looks more or less okay to me. The circle seems a bit pixelated compared to the [Lincoln Heritage shield](https://americanamap.org/#map=12/39.82335/-88.96325&language=en), which is also round. But, this might just be a perceptual issue.

image

**Comment by 1ec5** [comment]
Comparing the two shields from your 1× screenshots here and in #738, both appear as circles, but the antialiasing is slightly different because of the gray rim inside the causeway shield. The faux 3D effect on the Lincoln Heritage Trail shield also makes these shields more difficult to compare. To optimize the antialiasing at 1×, circular shields would need to be sized at a factor of 2&nbsp;pixels, such as 16×16&nbsp;pixels.

Lincoln Causeway

Lincoln Causeway

**Review by ZeLonewolf — APPROVED** [review]
Looks good to me.  The 16x16 versions are convincing that this is just a perceptual thing on my part.

**Comment by ZeLonewolf** [comment]
Oh, I see now that the problem was the parish boundary line running into the shield graphic...

**Pull request merged**
