### PR TITLE
Add British Columbia Shields

### PR DESCRIPTION
**Pull request by claysmalley**
Finishing off the West Coast, with Canada's portion of it.

Screenshot from 2022-04-06 20-33-56
Screenshot from 2022-04-06 20-34-23

In real life, British Columbia has a fixed-width shield. Letter-suffixed routes are common in Canada in situations where the United States may have bannered routes (`modifier=*`). British Columbia shields display the letter suffix in a smaller font size than the rest of the ref.

Americana can only produce a shield with a single font size, and it is not expected to support multiple font sizes in the future. This PR introduces a wider 3-character variant shield to compensate for the fixed font size. In addition, the British Columbia is flag is removed, the line art is simplified, and the colo(u)rs are changed to match the project's colo(u)r palette.

British Columbia routes 3 and 5 have unique shields that are derivatives of the standard BC shield, with additional artwork. This PR does not attempt to recreate these shields, due to copyright restrictions, space limitations and lack of tagging consensus.

BC-17
BC-97C

### CODE REVIEW

**Comment by ZeLonewolf** [comment]
I'm curious about the gray shield background rather than white?

**Comment by claysmalley** [comment]
I goofed up. Thanks for pointing that out.

**Comment by Pengor** [comment]
I think this looks pretty good, I will miss the fun British Columbia flag emblem, but don't really see a way to include it without shrinking the size of the font. Apple Maps includes it in their B.C. shields but it looks like they're working with more pixels (I measured 24w x 27h on my PC) 🤔

**Comment by claysmalley** [comment]
I added a tab on the top of the shields in place of the BC coat of arms, in response to some critique on the [talk-ca@openstreetmap.org mailing list.](https://lists.openstreetmap.org/listinfo/talk-ca) While I don't intend to copy the dimensions of the shield precisely, I think this looks good and matches the approach taken for the real-life shields of highways 3 and 5, which have the coat of arms removed to leave room for other artwork.

Screenshot from 2022-04-08 10-30-33
Screenshot from 2022-04-08 10-30-56

**Review by ZeLonewolf — APPROVED** [review]
Looks great!  I'll leave this open for a bit in case there's any more feedback from the talk-ca discussion.

**Comment by claysmalley** [comment]
I think this has gotten all the feedback it's gonna get. Same with #271 and #272. Are we ready to merge?

**Comment by ZeLonewolf** [comment]
Ship it!

**Comment by VA7DBI** [comment]
I just thought I'd put this here in case it's of use, the [standard road sign order catalog](https://www2.gov.bc.ca/assets/gov/driving-and-transportation/transportation-infrastructure/engineering-standards-and-guidelines/traffic-engineering-and-safety/traffic-engineering/traffic-signs-and-pavement-markings/standard-traffic-signs/standard-traffic-signs/guide_signs.pdf) for BC.

**Pull request merged**
