### PR TITLE
Add library icon

### LINKED ISSUE #821: Render libraries
Libraries are anchor institutions in a community, providing a variety of services. Rendering them in the style would make progress on #435 and #692.

An obvious rendering choice would be some sort of book. Carto and maki both have open books:
Screen Shot 2023-03-11 at 11 40 15 AM Screen Shot 2023-03-11 at 11 34 56 AM

A side profile is also a common icon (NPS and Rontgen):
image Screen Shot 2023-03-11 at 11 46 55 AM

Alternatively, we could evoke the MUTCD, which depicts a person reading:
Screen Shot 2023-03-11 at 11 46 55 AM image

Another option is a neoclassical columned building, as suggested for a museum (#820) or town hall (#794), maybe evoking a [Carnegie library](https://en.wikipedia.org/wiki/Carnegie_library#Gallery). But I fear that icon idea is too tied up in a specific detail of American history, and a book would be more distinctive and clear. We could even render bookstores with the same icon, but in a shop color. This is the approach Carto takes:
Screen Shot 2023-03-11 at 11 54 35 AM

I think libraries best fit into the "attraction" category, which is of undecided color in the style, maybe brown (see #820).

### PR DESCRIPTION
**Pull request by wmisener**
Fixes #821, and makes progress on #435 and #692. Adds an icon for libraries: poi_library
Based on feedback in #821, I riffed off the MUTCD I4-1 sign, which depicts a person reading and should be highly recognizable to an American audience.

I'd be open to an approach that uses a lone book symbol as well.

Went with blue coloring, based on discussions [like this](https://osmus.slack.com/archives/C01V02K52UX/p1691089744839109?thread_ts=1691041634.613469&cid=C01V02K52UX) and others. I think there's an argument to be made that libraries also fit the definition of "Attraction: places where people go for entertainment, leisure, or curiosity", which would be brown, but "community anchor"/"infrastructure" is probably more in line with current style symbology.

Previews:
UCLA ([localhost link](http://localhost:1776/#map=15.07/34.07068/-118.44458))
Screen Shot 2023-12-21 at 7 05 24 AM

Gallup, NM ([localhost link](http://localhost:1776/#map=15.13/35.526549/-108.740541))
Screen Shot 2023-12-21 at 7 29 51 AM

New York, NY ([localhost link](http://localhost:1776/#map=16.36/40.752812/-73.982632))
Screen Shot 2023-12-21 at 7 33 56 AM

Legend:
Screen Shot 2023-12-21 at 7 44 16 AM

### CODE REVIEW

**Comment by wmisener** [comment]
Based on feedback [on Slack](https://osmus.slack.com/archives/C01V02K52UX/p1703173827232079), a few variants/concepts:
A fatter (more well-rounded?) person in the MUTCD-style icon: poi_library_fatman
Screen Shot 2023-12-21 at 8 22 17 PM

An upright, cracked-open book, similar to the [NPS bookstore symbol](https://www.nps.gov/npgallery/GetAsset/cd253093-6813-471e-9d16-042c2a373a97): poi_library_uprightbook
Screen Shot 2023-12-21 at 8 28 30 PM

An open book, similar to the Carto symbol: poi_library_openbook
Screen Shot 2023-12-21 at 8 36 14 PM

I think any of these concepts would work well! The latter two do have the advantage that the same symbol in the consumer color could easily be reused for bookstores.

**Comment by claysmalley** [comment]
I like the NPS bookstore icon. It clearly represents a book (which is hard to discern in the MUTCD icon, IMO), and it looks good in context with other icons. And of course, bonus points for potential reuse in a different color for bookstores.

**Comment by ZeLonewolf** [comment]
Please add location 17/40.753326/-73.982224 to test/sample_locations.json

**Comment by wmisener** [comment]
Done, and I updated the icon in the PR to have the upright/NPS-style book icon for libraries. There was consensus on Slack that this icon would be great for bookstores, which I'll do in a separate PR, and some discussion on whether it would be better to use the same icon or slightly different icons for bookstores and libraries. I'm definitely team same-icon, as I think the style is much more intuitive and coherent that way. But I'm open to other opinions.

**Review by ZeLonewolf — APPROVED** [review]
This looks great!  Thanks for working on this.

**Pull request merged**
