### PR TITLE
Factor out pill shield function

### PR DESCRIPTION
**Pull request by claysmalley**
Just the parts of #323 that had broad consensus.

### CODE REVIEW

**Comment by ZeLonewolf** [comment]
The code looks essentially correct, and I appreciate the consolidation and reduction in line count!  I just haven't had the opportunity yet to run the code and independently confirm everything is working.

**Comment by ZeLonewolf** [comment]
I've noticed an issue with shrinkage in the pill shield that I can't explain.

Current Americana:
image

PR:
image

**Comment by claysmalley** [comment]
That was a result of me changing the corner radius from 8 to 10 to make it more circley. I haven't taken a look at `roundedRectShield()` to figure out why it does that.

**Comment by ZeLonewolf** [comment]
Oh yeah, that makes sense.  I think the layout math excludes the corner arcs entirely rather than trying to bring the layout area up to the edge of it.  So probably need to add the arc radius times square root of two "somewhere" in that math...

**Comment by claysmalley** [comment]
`roundedRectTextConstraint()` now returns the value of `ellipseTextConstraint()` instead if it is passed a `radius` of `8` or greater:

Screenshot from 2022-05-19 17-33-25
Screenshot from 2022-05-19 17-33-38

**Comment by claysmalley** [comment]
Fixes #301.

Screenshot from 2022-05-19 17-49-45 Screenshot from 2022-05-19 17-52-11

**Comment by ZeLonewolf** [comment]
Oh you fixed the clipping bug!  So awesome.

**Pull request merged**
