### PR TITLE
Refactor circle/ellipse draw functions to JSON

### PR DESCRIPTION
**Pull request by ZeLonewolf**
A followup from #701.  This PR converts circle and ellipse draw functions to JSON.

### CODE REVIEW

**Review by claysmalley — APPROVED** [review]
Looks good to me.
Screenshot from 2023-01-16 20-31-08

**Comment by michaelblyons** [comment]
Does it not look like there's more padding above the number than below?

**Comment by ZeLonewolf** [comment]
Yes, it does.  There might be an issue with padding or text constraint.  Please open a bug.

**Comment by ZeLonewolf** [comment]
Partial implementation of #118

**Pull request merged**
