### PR TITLE
Add shx to make npm scripts run on Windows CMD and PowerShell

### PR DESCRIPTION
**Pull request by zekefarwell**
This PR adds [shelljs/shx](https://github.com/shelljs/shx) to make project scripts platform independent instead of requiring a bash shell.  The primary purpose of this is to it easier to run the project on Windows.  The only Windows requirement after this should be to install Node.js (and git obviously).

### CODE REVIEW

**Comment by claysmalley** [comment]
I don't have Windows, so unless we need to test that it works on Linux, there's nothing I can do.

**Comment by zekefarwell** [comment]
Yup just wanting to make sure the change doesn't cause any problem for other platforms

**Comment by claysmalley** [comment]
Build is successful on Linux. Everything's working :smile:

**Comment by zekefarwell** [comment]
Oh right, @Pengor is another Windows user who can test this

**Review by Pengor — APPROVED** [review]
Yep, builds and runs on Windows (checked with both `pwsh` and `cmd`) 👍

**Review by ZeLonewolf — APPROVED** [review]
Works great on Windows CMD and WSL.

**Comment by ZeLonewolf** [comment]
There are conflicts here because some jerks decided to reorganize the repository 😂

**Comment by zekefarwell** [comment]
should have merged this simple change first 😄

**Comment by jleedev** [comment]
Should be good.

**Pull request merged**
