### PR TITLE
TagInfo: capital=yes is equivalent to capital=2

### PR DESCRIPTION
**Pull request by Blijbol**
See:
https://github.com/openmaptiles/openmaptiles/blob/master/layers/place/capital.sql

### CODE REVIEW

**Comment by ZeLonewolf** [comment]
Huh.  Curious.  Looks like `capital=2` is barely used in fact.

Is it permissible to set an array in the "values" block? @1ec5 ?

**Comment by Blijbol** [comment]
> Is it permissible to set an array in the "values" block?

The [documentation](https://wiki.openstreetmap.org/wiki/Taginfo/Projects) does not mention such a possibility.

**Review by ZeLonewolf — APPROVED** [review]
Looks good to me in concept.  Another maintainer should sanity check before merging.

**Review by 1ec5 — APPROVED** [review]
Unfortunately, [`value` is required to be a `string`](https://github.com/taginfo/taginfo-projects/blob/e577219b5a74b570146af0e84b9b9b74ddf58a21/taginfo-project-schema.json#L93). This looks good to me.

**Pull request merged**
