### PR TITLE
Blue hexagon shields for Pakistan National Highways

### PR DESCRIPTION
**Pull request by bgo-eiu**
As this shape is already included in the repository for Japanese prefectural shields, this PR changes the name of the SVG file for the blue hexagonal shield shape from a country specific description to `hexagon_blue`. The `shield_defs.js` file has then been updated to reflect these changes for Japanese prefectural shields, and to include the Pakistan National Highway shields described in #396 using the same parameters.

### CODE REVIEW

**Comment by bgo-eiu** [comment]
Example, N-5 at Torkham 
image

**Review by claysmalley — CHANGES_REQUESTED** [review]
We'll need a better naming scheme to distinguish horizontally-oriented and vertically-oriented hexagon shields. I would recommend adding `horizontal` to the blue hexagon shield's filename. I gave the following shield the name `shield40_hexagon_wide_green.svg`, but `wide` should probably be changed to `vertical`:



Text inside this shield is very small when it has 4 or more characters. The photos in #396 indicate that the hexagon can be horizontally expanded to accommodate longer text, so let's make a variant of this SVG with a width somewhere between 25 and 30 pixels, whatever looks right:

Screenshot from 2022-06-13 08-54-00

**Comment by ZeLonewolf** [comment]
Horizontal means the pointy ends east and west, right?

**Comment by claysmalley** [comment]
That's what I'm thinking. Two of the six sides of the hexagon run horizontally.

**Comment by claysmalley** [comment]
Here's a wider hexagon I think matches the real-life signs a little better:

shield40_hexagon_horizontal_blue_3

Don't worry about renaming the files; I'll refactor it all eventually.

**Comment by bgo-eiu** [comment]
Oh thank you! I've been waiting to have time to make a green semi circle SVG for the motorways and one for Lahore Ring Road. I heard back from the active Pakistani route mapper and they said the tags I suggested for those are fine so long as I don't change any of the tags that relate to them being controlled access highways.

**Comment by ZeLonewolf** [comment]
Setting to draft pending shield update

**Comment by claysmalley** [comment]
Here's a motorway shield:

shield40_pk_motorway

I played around with the Lahore Ring Road shield and I couldn't manage to make the text big enough to be legible. This route may need an `ovalShield` or `pillShield` treatment.

**Comment by claysmalley** [comment]
Shields are up and running:

Screenshot from 2022-07-13 18-07-34

**Review by 1ec5 — APPROVED** [review]
This looks good to go. We can continue to track provincial and district roads in #396.

**Review by claysmalley — APPROVED** [review]

**Pull request merged**
