### PR TITLE
Add Tennessee shields

### LINKED ISSUE #303: Tennessee shields
Tennessee has one "network" of state highways, though signage can shift between either of two shields depending on a segment's importance in the road hierarchy. Route numbers can have up to 3 digits.

Existing relations are tagged with `network=US:TN`, conflating both shields into one network. There has been some previous discussion towards new network values that correspond to shield appearance, but none so far have produced the change in tagging guidelines necessary for renderers to support Tennessee highway shields.

Primary shield:
Tennessee_155

Secondary shield:
Secondary_Tennessee_171

### PR DESCRIPTION
**Pull request by claysmalley**
Fixes #303.

Screenshot from 2022-06-19 13-23-43 Screenshot from 2022-06-19 13-23-21

### CODE REVIEW

**Comment by ZeLonewolf** [comment]
I'm seeing seeing default shields all over the place.  Are we awaiting a tagging or render update?

image

**Comment by zekefarwell** [comment]
That's mapper feedback 😀.  Most routes are still tagged `network=US:TN`, and need to be updated to the primary/secondary scheme.
https://taginfo.openstreetmap.org/search?q=network%3DUS%3ATN

**Review by ZeLonewolf — APPROVED** [review]
Okay I found the test area along I-81 😬 

Looks good!

**Review by 1ec5 — APPROVED** [review]
Thanks!

**Pull request merged**
